# -*- coding: utf-8 -*-
"""Caleb_Thurston_Homework1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1lVa6jviykLsALAn-ougWx9rI3XFJ_bJ6
"""

#   Code Done by   |\___/|             
# Caleb A. Thurston)     (    
#       (CAT)     =\     /=  
#     (9/14/22)     )===(    
#                  /     \  
#                  |     |    
#                 /       \   
#                 \       /      
#          _/\_/\_/\_   _/_/\_/\_


#Assignment Description:
#Write a short program that calculates how much flour, granulated sugar, 
#brown sugar, butter, eggs, and chocolate chips will be needed for a given number 
#of bakers making a given number of cookies. All ingredients except eggs should 
#be reported in quantities of cups.

#Needs:
#Number of bakers variable (input variable)
#Each Baker needs enough ingredients for 24 cookies (plus extra)
#Hot-swappable number of cookies 
#Required Calculations, Flour, Granulated Sugar, brown sugar, butter, chocolate chips, eggs

NUM_BAKERS = int(input("How many bakers are there? "))
#BUFFER = int(input("How many cups/eggs extra do you want? "))
NUM_COOKIES = int(input("How many cookies per baker?"))
#Number of ingredients per 24 cookies in cups (except eggs)
NUM_BUFFER = int(input("Choose how much of a buffer you want! "))
#User chosen buffer incase there's a mess up with ingredients

FLOUR = 3
GRANULATED_SUGAR = 1
BROWN_SUGAR = 1
BUTTER = 1
CHOCOLATE_CHIPS = 2
EGGS = 2
WALNUTS = 1


def betterCalc(bakers, cookies, buffer):
  
  flour = int((FLOUR/24 * NUM_COOKIES) * NUM_BAKERS) + buffer
  granulatedSugar = int((GRANULATED_SUGAR/24 * NUM_COOKIES) * NUM_BAKERS) + buffer
  brownSugar = int((BROWN_SUGAR/24 * NUM_COOKIES) * NUM_BAKERS) + buffer
  butter = int((BUTTER/24 * NUM_COOKIES) * NUM_BAKERS) + buffer
  chocolateChips = int((CHOCOLATE_CHIPS/24 * NUM_COOKIES) * NUM_BAKERS) + buffer
  eggs = int((EGGS/24 * NUM_COOKIES) * NUM_BAKERS) + buffer
  walnuts = int((WALNUTS/24 * NUM_COOKIES) * NUM_BAKERS) + buffer

#message to display what's needed
  finalMsg = "{} amount of cookies for {} amount of bakers needs {} cups of flour, {} cups of granulated sugar, {} cups of brown sugar, {} cups of butter, {} cups of chocolate chips, {} eggs, {} cups of chopped walnuts"
  print(finalMsg.format(NUM_COOKIES,NUM_BAKERS,flour,granulatedSugar,brownSugar,butter,chocolateChips,eggs,walnuts))

betterCalc(NUM_BAKERS,NUM_COOKIES,NUM_BUFFER)