# -*- coding: utf-8 -*-
"""class and subclass practice s.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1E0eUukOhhzwDbBaL_45H_0gzeI_p9sCA
"""

class dog:
  def __init__(self,dogBreed,age,training,coat):
    self.dogBreed = dogBreed
    self.age = age
    self.training = training
    self.coat = coat
  def list_dog_stats(self):
    print(
    '\n', "Breed:", self.dogBreed,
    '\n', "Dog's Age:", self.age,
    '\n', "Dog's Training:", self.training,
    '\n', "Coat Color:", self.coat)


class smallDog(dog):
  def __init__(self,dogBreed,age,training,coat,needs,noise):
    super().__init__(self,dogBreed,age,training,coat)
    self.needs = needs
    self.noise = noise



scruffy = smallDog("Yorkie", "3","Potty Training","Brown", "low", "high")
scruffy.list_dog_stats()