# -*- coding: utf-8 -*-
"""Nested Functions Testing.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Axi2ctotRBp-SZFk4d6paF9dBYub2-XL
"""

typeOfJuice = input("What type of juice would you like? ")
juiceAmount = float(input("How many of this juice would you like? "))

def juiceType1(juiceType):
  def howMany(amount):
    if juiceType == "Orange Juice":
      return amount * 1.99
    if juiceType == "Apple Juice":
      return amount * 1.49
    if juiceType == "Milk":
      return amount * 2.49
  return howMany


yourTotal = juiceType1(typeOfJuice)(juiceAmount)
msg = "Your total for your juice is {}!"
print(msg.format(yourTotal))