# -*- coding: utf-8 -*-
"""Zipped variables example.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1bVO2Kj4mSS2b-512hefDSZXGJQEnCEpF
"""

color1 = []

color2 = []


firstColor = input("Input your first color set (3 colors) ")
for i in (1,4):
  color1.append(firstColor)
  firstColor = input("Input your first color set (3 colors) ")
  color1.append(firstColor)
  i += 1

secondColor = input("Input your second color set (3 colors) ")
for i in (1,4):
  color2.append(secondColor)
  secondColor = input("Input your second color set (3 colors) ")
  color2.append(secondColor)
  i += 1

for x,y in zip(color1,color2):
  print(x,y)